### ISSUE TITLE
Images cannot be displayed on the tutorial page

### ISSUE THREAD

**Issue by semihbkgr** [hazelcast-guides/airline-connections#15]
Images cannot be displayed on the tutorial page.

**Comment by Serdaro** [comment]
@semihbkgr , could you please check again?

**Comment by semihbkgr** [comment]
It is good 👍 
seems fixed after https://github.com/hazelcast-guides/airline-connections/commit/05b20ec517ef0b636f8d38df40ad3c7807b52f2b
