### ISSUE TITLE
Docs reference non-existent 'Management Center'

### ISSUE THREAD

**Issue by benheymink** [hazelcast-guides/airline-connections#19]
Following the tutorial [here](https://docs.hazelcast.com/tutorials/airline-connections#step-4-submit-job), I'm instructed to:

```
Go to the dashboard for your cluster and open Management Center.

In Management Center, select Stream Processing > Jobs
```

I can't seem to find this anywhere!

**Comment by benheymink** [comment]
For reference, this is what I see both on the homepage, and when I drill into my cluster:

<img width="1376" alt="Screenshot 2024-01-30 at 08 10 27" src="https://github.com/hazelcast-guides/airline-connections/assets/824764/23d9faff-6ad4-4dce-b8f1-bebe4d69bc11">
<img width="1378" alt="Screenshot 2024-01-30 at 08 10 45" src="https://github.com/hazelcast-guides/airline-connections/assets/824764/7d6df65d-e02a-415c-8b59-393444c79cbb">

**Comment by rebekah-lawrence** [comment]
Thank you for your feedback @benheymink . We'll look into it and get that content updated.

**Comment by rebekah-lawrence** [comment]
Apologies for the delay. The issue you faced is that Management Center is not available in the Cloud Trial. In the Trial, you can see the size of my-map increase as the entries are written.

I have clarified this in the tutorial, which is now live.

Thank you for pointing this issue out.
